### ISSUE TITLE
Combine the two "install" buttons into one

### ISSUE THREAD

**Issue by bumi** [getAlby/alby-installer-macos#3]
Currently we first tell the use to install the browser extension (by opening the browser with a URL) and then to install the companion app. 

We can actually combine that into one Button. We create the manifest JSON for that browser and then we open the browser with the install URL.

**Comment by stuffmc** [comment]
Totally feasible. It doesn't mean people will install the extension though and maybe it's installed already, which we might check in the future and then not open the browser. Also, the extension probably does check that the companion has been installed, right?

**Comment by bumi** [comment]
Nice. yep, the extension then checks if the companion is installed.
