### ISSUE TITLE
Make sure we have builds for all different platforms

### ISSUE THREAD

**Issue by bumi** [getAlby/alby-installer-macos#6]
What do we need to do to make sure that the app runs on all recent macs (M1, Intel, recent OS versions)? 
This is for the installer itself but also the companion executable. Do we need to deliver different executables for the different platforms?

**Comment by stuffmc** [comment]
No.

**Comment by bumi** [comment]
@dylancom had the issue opening the app: "you can’t open alby because it’s not supported on this mac"
and I am not sure how the Rust app needs to be compiled.

**Comment by bumi** [comment]
the companion executable works on Intel and on M1.

we just need to make sure that the .app is available for intel and m1 and recent OS versions

**Comment by bumi** [comment]
so it actually seems we need to have two different executables depending on the platform. ?
need to see how to create a universal binary

https://stackoverflow.com/questions/66849112/how-do-i-cross-compile-a-rust-application-from-macos-x86-to-macos-silicon

**Comment by stuffmc** [comment]
LOL what kind of old school technology is that? Can't it produce a universal binary?! Do I to change the "path" to, say, `alby-intel` or `alby-arm`? :) I can also probably make 2 executables/`.app` but that isn't the way a Mac is supposed to work.

**Comment by bumi** [comment]
chill, I just have to learn how to build the binaries. 
you know web developers don't deal with this. 
and btw. Rust is younger than Swift. :)

**Comment by bumi** [comment]
I don't know the macOS and Rust world very well, but I think we now got universal builds:
https://github.com/getAlby/alby-companion-rs#build

this release contains the latest version and should run on M1 + Intel: https://github.com/getAlby/alby-companion-rs/releases/tag/v0.5.0
